In [1]:
import pandas as pd
import numpy as np

df_1 = pd.read_csv(
    "/home/sunshuo/qml/Competition/competition-examples/TradeMaster-competition/TradeMaster-bundle/data_public/test_input/test_input_1.csv",
    index_col=0)
df_1_next = pd.read_csv(
    "/home/sunshuo/qml/Competition/competition-examples/TradeMaster-competition/TradeMaster-bundle/data_private/next_test_input_1.csv",
    index_col=0)

In [5]:
df_1.index.unique()

Int64Index([0, 30, 60, 90, 120, 150, 180, 210, 240], dtype='int64')

In [6]:
df_1_next.index.unique()

Int64Index([1, 31, 61, 91, 121, 151, 181, 211, 241], dtype='int64')

In [13]:
from fileinput import close
return_rate_list_all=[]

for index in df_1.index.unique():
    single_date_information=df_1[df_1.index==index]
    single_date_information_next=df_1_next[df_1_next.index==index+1]
    close_today=single_date_information["close"]
    close_nextday=single_date_information_next["close"]
    return_rate_list=(close_nextday.values/close_today.values-1)
    return_rate_list_all.append(return_rate_list)
return_rate_list_all

[array([0.01236373, 0.00485304, 0.00533715, 0.04395227, 0.0081801 ,
        0.00549229, 0.00045497, 0.02703342, 0.00427741, 0.02237733,
        0.00807053, 0.00245256, 0.01775051, 0.01892495, 0.01175717]),
 array([-0.00863642, -0.01307246, -0.00054443, -0.03266522, -0.01176473,
        -0.0026246 ,  0.00194595, -0.00959131, -0.01845099, -0.00908101,
         0.00758214,  0.00802383,  0.00633485, -0.00388032,  0.00048293]),
 array([ 0.00695864,  0.00144689,  0.02212956, -0.00690953,  0.00375215,
         0.03233118,  0.00522144,  0.00916117,  0.02411661,  0.00195723,
         0.00819001, -0.00124386, -0.00022517,  0.0085938 , -0.00924858]),
 array([ 0.01984473, -0.00273734,  0.01992466,  0.02618578,  0.00899733,
         0.02737658,  0.00781101,  0.02615299, -0.02601772,  0.0277584 ,
        -0.00550061,  0.01645211,  0.00353744,  0.02481022,  0.00152974]),
 array([ 0.012546  ,  0.00065932, -0.02755974, -0.03389966, -0.00018489,
         0.01116307, -0.0018847 , -0.03084814, -0.00998037